version: 2
jobs:
  build:
    docker:
      - image: "ubuntu:latest"
    branches:
      only:
      - feature/add_circle-ci_support
    steps:
      - run:
          name: Install Git
          command: 'apt-get update && apt-get install git'
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && apt-get install -y cmake'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Listing
          command: 'ls -lrt /root/project/build'
      - run:
          name: Listing2
          command: 'ls -lrt /root/project/build/CMakeFiles'
      - run:
          name: Listing3
          command: 'cat /root/project/build/CMakeFiles/CMakeOutput.log' 
      - run:
          name: ETL Unit Testing
          command: './bin/etl'